
source 'git@github.com:HJ2018/HYNBase.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HYNMain_Example' do
  pod 'HYNMain', :path => '../'

  target 'HYNMain_Tests' do
    inherit! :search_paths

    
  end
end
